//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zebpay_Jayesh
{
    using System;
    using System.Collections.Generic;
    
    public partial class Currency
    {
        public long id { get; set; }
        public string fromcurrency { get; set; }
        public string tocurrency { get; set; }
        public decimal rate { get; set; }
    }
}
